<?php


namespace yuankezhan\yiiTableWidget;

use yii\base\Widget as YiiWidget;
class TableRows extends YiiWidget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}